name: family_expense_tracker
description: A budgeting, expense tracking and bill reminding app that allows
  shared control of budgetbooks

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_custom_dropdown: ^1.5.0
  animations: ^2.0.7
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  cloud_firestore: ^4.8.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dart_jsonwebtoken: ^2.8.2
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_secure_storage: ^8.0.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  lottie: ^2.4.0
  math_expressions: ^2.4.0
  mobile_scanner: ^3.3.0
  path: ^1.8.3
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.1.1
  sentry_flutter: ^7.8.0
  shared_preferences: ^2.2.0
  time: ^2.1.3
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
