name: family_expense_tracker
description: A budgeting, expense tracking and bill reminding app that allows
  shared control of budgetbooks

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_custom_dropdown: ^1.5.0
  animations: ^2.0.7
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  cloud_firestore: ^4.5.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  dart_jsonwebtoken: ^2.7.1
  expandable: ^5.0.1
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  hooks_riverpod: ^2.3.4
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  lottie: ^2.3.2
  math_expressions: ^2.4.0
  path: ^1.8.2
  path_provider: ^2.0.14
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  riverpod_annotation: ^2.0.4
  sentry_flutter: ^7.4.1
  shared_preferences: ^2.1.0
  time: ^2.1.3
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
